-- ============================================================================
-- Durable SIM800L SMS outbox
-- ============================================================================
-- The ESP32 uploads every machine SMS event here before it sends anything via
-- GSM. Rows remain pending after a modem failure, allowing later retry without
-- blocking newer pending rows.

CREATE TABLE IF NOT EXISTS public.sms (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_event_id TEXT NOT NULL UNIQUE,
  machine_id      TEXT NOT NULL,
  event_type      TEXT NOT NULL CHECK (
                    event_type IN (
                      'dispensed_product',
                      'payment',
                      'theft_alert',
                      'low_stock'
                    )
                  ),
  recipient       VARCHAR(30) NOT NULL,
  message         VARCHAR(320) NOT NULL,
  status          TEXT NOT NULL DEFAULT 'pending'
                  CHECK (status IN ('pending', 'sent')),
  attempt_count   INTEGER NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
  last_attempt_at TIMESTAMPTZ,
  last_error      VARCHAR(255),
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  sent_at         TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS sms_pending_queue_idx
  ON public.sms (id)
  WHERE status = 'pending';

-- Server timestamps prevent the ESP32's local clock from affecting delivery
-- history. The ESP32 increases attempt_count only after a modem failure.
CREATE OR REPLACE FUNCTION public.stamp_sms_delivery()
RETURNS trigger
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public
AS $$
BEGIN
  IF NEW.status = 'sent' AND OLD.status = 'pending' THEN
    NEW.sent_at := now();
    NEW.last_attempt_at := now();
    NEW.last_error := NULL;
  ELSIF NEW.status = 'pending' AND NEW.attempt_count > OLD.attempt_count THEN
    NEW.last_attempt_at := now();
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS stamp_sms_delivery ON public.sms;
CREATE TRIGGER stamp_sms_delivery
BEFORE UPDATE ON public.sms
FOR EACH ROW EXECUTE FUNCTION public.stamp_sms_delivery();

-- Keep permissions consistent with the current firmware tables. The existing
-- project has RLS disabled; a future Auth/RLS rollout should replace this.
ALTER TABLE public.sms DISABLE ROW LEVEL SECURITY;
GRANT ALL ON TABLE public.sms TO anon, authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.sms_id_seq TO anon, authenticated;

-- Optional realtime support lets the dashboard observe the SMS queue.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime'
      AND schemaname = 'public'
      AND tablename = 'sms'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.sms;
  END IF;
END $$;

NOTIFY pgrst, 'reload schema';
