-- Historical ESP32 resource telemetry for the Device Health dashboard charts.
CREATE TABLE IF NOT EXISTS public.device_resource_logs (
  id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  machine_id                  TEXT NOT NULL,
  internal_sram_total_bytes   BIGINT NOT NULL,
  internal_sram_free_bytes    BIGINT NOT NULL,
  external_psram_total_bytes  BIGINT NOT NULL,
  external_psram_free_bytes   BIGINT NOT NULL,
  external_flash_total_bytes  BIGINT NOT NULL,
  external_flash_used_bytes   BIGINT NOT NULL,
  filesystem_total_bytes      BIGINT NOT NULL,
  filesystem_used_bytes       BIGINT NOT NULL,
  rom_total_bytes             BIGINT NOT NULL,
  cpu_temperature_c           NUMERIC(5,2),
  collected_at                TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS device_resource_logs_collected_at_idx
  ON public.device_resource_logs (collected_at DESC);

ALTER TABLE public.device_resource_logs DISABLE ROW LEVEL SECURITY;
GRANT ALL ON TABLE public.device_resource_logs TO anon, authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.device_resource_logs_id_seq TO anon, authenticated;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime'
      AND schemaname = 'public'
      AND tablename = 'device_resource_logs'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.device_resource_logs;
  END IF;
END $$;

NOTIFY pgrst, 'reload schema';
