ALTER TABLE public.machine_settings
  ADD COLUMN IF NOT EXISTS enable_pin_connection_detection BOOLEAN NOT NULL DEFAULT FALSE;

CREATE TABLE IF NOT EXISTS public.esp32_pin_status (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  machine_id        TEXT NOT NULL,
  gpio              INTEGER NOT NULL,
  pin_label         TEXT NOT NULL,
  current_mode      TEXT NOT NULL,
  connection_status TEXT NOT NULL CHECK (connection_status IN ('connected', 'disconnected')),
  realtime_value    TEXT NOT NULL,
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (machine_id, gpio)
);

CREATE INDEX IF NOT EXISTS esp32_pin_status_machine_updated_idx
  ON public.esp32_pin_status (machine_id, updated_at DESC);

ALTER TABLE public.esp32_pin_status DISABLE ROW LEVEL SECURITY;
GRANT SELECT ON TABLE public.esp32_pin_status TO anon, authenticated;
REVOKE INSERT, UPDATE, DELETE ON TABLE public.esp32_pin_status FROM anon, authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.esp32_pin_status_id_seq TO anon, authenticated;

CREATE OR REPLACE FUNCTION public.sync_esp32_pin_status(
  p_device_key text,
  p_machine_id text,
  p_pins jsonb
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  expected_device_key text;
  pin jsonb;
BEGIN
  SELECT device_api_key INTO expected_device_key
  FROM machine_settings
  ORDER BY id DESC
  LIMIT 1;

  IF expected_device_key IS NULL OR p_device_key IS DISTINCT FROM expected_device_key THEN
    RETURN jsonb_build_object('success', false, 'message', 'invalid device key');
  END IF;

  IF p_machine_id <> 'VM001' OR jsonb_typeof(p_pins) <> 'array' THEN
    RETURN jsonb_build_object('success', false, 'message', 'invalid pin status payload');
  END IF;

  FOR pin IN SELECT value FROM jsonb_array_elements(p_pins)
  LOOP
    INSERT INTO esp32_pin_status (
      machine_id, gpio, pin_label, current_mode, connection_status, realtime_value, updated_at
    ) VALUES (
      p_machine_id,
      (pin ->> 'gpio')::integer,
      pin ->> 'pin_label',
      pin ->> 'current_mode',
      pin ->> 'connection_status',
      pin ->> 'realtime_value',
      now()
    )
    ON CONFLICT (machine_id, gpio) DO UPDATE SET
      pin_label = EXCLUDED.pin_label,
      current_mode = EXCLUDED.current_mode,
      connection_status = EXCLUDED.connection_status,
      realtime_value = EXCLUDED.realtime_value,
      updated_at = EXCLUDED.updated_at;
  END LOOP;

  RETURN jsonb_build_object('success', true);
END;
$$;

GRANT EXECUTE ON FUNCTION public.sync_esp32_pin_status(text, text, jsonb) TO anon, authenticated;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime' AND schemaname = 'public'
      AND tablename = 'esp32_pin_status'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.esp32_pin_status;
  END IF;
END $$;

NOTIFY pgrst, 'reload schema';
