-- Device catalog and per-PIN assignment for the ESP32 connection inspector.
CREATE TABLE IF NOT EXISTS public.esp32_pin_devices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL CHECK (char_length(btrim(name)) BETWEEN 1 AND 100),
  image_url TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.esp32_pin_device_assignments (
  machine_id TEXT NOT NULL,
  gpio INTEGER NOT NULL CHECK (gpio BETWEEN 0 AND 39),
  device_id BIGINT NOT NULL REFERENCES public.esp32_pin_devices(id) ON DELETE CASCADE,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (machine_id, gpio)
);

CREATE INDEX IF NOT EXISTS esp32_pin_device_assignments_device_idx
  ON public.esp32_pin_device_assignments (device_id);

ALTER TABLE public.esp32_pin_devices DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.esp32_pin_device_assignments DISABLE ROW LEVEL SECURITY;

GRANT SELECT ON public.esp32_pin_devices, public.esp32_pin_device_assignments TO anon, authenticated;
REVOKE INSERT, UPDATE, DELETE ON public.esp32_pin_devices, public.esp32_pin_device_assignments FROM anon, authenticated;

CREATE OR REPLACE FUNCTION public.create_esp32_pin_device(
  p_name TEXT,
  p_image_url TEXT DEFAULT ''
)
RETURNS public.esp32_pin_devices
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  created_device public.esp32_pin_devices;
  normalized_name TEXT := btrim(p_name);
  normalized_image_url TEXT := btrim(COALESCE(p_image_url, ''));
BEGIN
  IF char_length(normalized_name) NOT BETWEEN 1 AND 100 THEN
    RAISE EXCEPTION 'device name must be between 1 and 100 characters';
  END IF;

  IF normalized_image_url <> '' AND normalized_image_url !~* '^https?://.+' THEN
    RAISE EXCEPTION 'image link must start with http:// or https://';
  END IF;

  INSERT INTO public.esp32_pin_devices (name, image_url)
  VALUES (normalized_name, normalized_image_url)
  RETURNING * INTO created_device;

  RETURN created_device;
END;
$$;

CREATE OR REPLACE FUNCTION public.assign_esp32_pin_device(
  p_machine_id TEXT,
  p_gpio INTEGER,
  p_device_id BIGINT
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF p_machine_id <> 'VM001' OR p_gpio NOT BETWEEN 0 AND 39 THEN
    RETURN jsonb_build_object('success', false, 'message', 'invalid machine or GPIO');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM public.esp32_pin_devices WHERE id = p_device_id) THEN
    RETURN jsonb_build_object('success', false, 'message', 'device not found');
  END IF;

  INSERT INTO public.esp32_pin_device_assignments (machine_id, gpio, device_id, updated_at)
  VALUES (p_machine_id, p_gpio, p_device_id, now())
  ON CONFLICT (machine_id, gpio) DO UPDATE
  SET device_id = EXCLUDED.device_id, updated_at = EXCLUDED.updated_at;

  RETURN jsonb_build_object('success', true);
END;
$$;

GRANT EXECUTE ON FUNCTION public.create_esp32_pin_device(TEXT, TEXT) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.assign_esp32_pin_device(TEXT, INTEGER, BIGINT) TO anon, authenticated;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime' AND schemaname = 'public'
      AND tablename = 'esp32_pin_devices'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.esp32_pin_devices;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime' AND schemaname = 'public'
      AND tablename = 'esp32_pin_device_assignments'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.esp32_pin_device_assignments;
  END IF;
END $$;

NOTIFY pgrst, 'reload schema';
